# Generated by Django 3.0.3 on 2020-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, null=True, verbose_name='header')),
                ('body', models.TextField(default='Empty post...', verbose_name='text_of_post')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('views_count', models.IntegerField(default=0, verbose_name='views count')),
            ],
        ),
    ]
