# Generated by Django 3.0.3 on 2020-06-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='rubric')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='rubric description')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date', 'views_count'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='text of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(help_text='write your header of post', max_length=100, null=True, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, unique=True, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_priority', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.Post')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.Rubric')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='rubrics',
            field=models.ManyToManyField(through='board.Kit', to='board.Rubric'),
        ),
    ]
