# Generated by Django 3.0.3 on 2020-06-23 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_auto_20200620_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='rubric_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='comment')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='time commented')),
                ('rating', models.SmallIntegerField(default=0, editable=False, verbose_name='rating')),
                ('sender_email', models.EmailField(default='anon@ya.ru', max_length=254, verbose_name='email of sender')),
                ('answer_to_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Comment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='author of comment')),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Post', verbose_name='comment for a post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
